---
# https://sports.yahoo.com/nhl/players/<player-id>/
skaters:
    1:
      id: 7109
      name: Matthews, Auston
      positions: 
        - C
    2: 
      id: 5431
      name: Trocheck, Vincent
      positions: 
        - C
    3:
      id: 4471
      name: Stamkos, Steven
      positions: 
        - LW
        - RW
    4:
      id: 7110
      name: Laine, Patrik
      positions: 
        - LW
        - RW
    5: 
      id: 5381
      name: Murphy, Connor
      positions: 
        - D
    6: 
      id: 6476
      name: Toews, Devon
      positions: 
        - D
    7: 
      id: 6759
      name: Connor, Kyle
      positions: 
        - LW
    8:
      id: 5104
      name: Klingberg, John
      positions: 
        - D
    9:
      id: 4779
      name: Foligno, Marcus
      positions: 
        - LW
        - RW
    10:
      id: 6376
      name: Ritchie, Nick
      positions: 
        - LW
    11:
      id: 7527
      name: Necas, Martin
      positions: 
        - C
        - RW
    12:
      id: 3358
      name: Burns, Brent
      positions: 
        - D
    13:
      id: 6766
      name: Konecny, Travis
      positions: 
        - RW
        - IR
    14:
      id: 6758
      name: Barzal, Matthew
      positions: 
        - C
    15:
      id: 7112
      name: Puljujarvi, Jesse
      positions: 
        - RW
    16:
      id: 6754
      name: Gurianov, Denis
      positions: 
        - LW
        - RW
    17:
      id: 4691
      name: Ellis, Ryan
      positions: 
        - D
    18:
      id: 4792
      name: Tatar, Tomas
      positions: 
        - LW
        - RW
    19:
      id: 7493
      name: Iafallo, Alex
      positions: 
        - LW
    20:
      id: 6377
      name: Fiala, Kevin
      positions: 
        - LW
        - RW
    21:
      id: 6002
      name: Burakovsky, Andre
      positions: 
        - LW
        - RW
    22:
      id: 4961
      name: Hall, Taylor
      positions: 
        - LW
goalies:
    1:
      id: 4369
      name: Reimer, James
      positions: 
        - G
    2 :
      id: 5853
      name: Ullmark, Linus
      positions: 
        - G
        - IR
    3:
      id: 4365
      name: Bishop, Ben
      positions: 
        - G
        - IR
